name: deploy-api-docs

on:  
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: krdlab/setup-haxe@v1
      - name: Setup
        run: haxelib install dox
      - name: Build documentation
        run: |
          cd api
          haxe api.hxml -xml build/api.xml -D doc-gen
          haxe dox.hxml
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: api/pages
